[package]
name = "magnus"
version = "0.3.2"
authors = ["Mat Sadler <mat@sourcetagsandcodes.com>"]
edition = "2018"
resolver = "2"
description = "High level Ruby bindings for Rust."
keywords = ["ruby"]
categories = ["api-bindings", "development-tools::ffi"]
repository = "https://github.com/matsadler/magnus"
homepage = "https://github.com/matsadler/magnus"
documentation = "https://docs.rs/magnus/"
license = "MIT"
exclude = [".github", ".gitignore", "build-sys/"]

[workspace]
members = ["magnus-macros"]
exclude = ["examples/rust_blank/ext/rust_blank", "examples/custom_exception_ruby/ext/ahriman", "examples/custom_exception_rust/ext/ahriman"]

[features]
embed = []
rb-sys-interop = ["rb-sys"]
ruby-abi-version = ["rb-sys/ruby-abi-version"]
global-allocator = ["rb-sys/global-allocator"]
ruby-static = ["rb-sys/ruby-static"]

[dependencies]
magnus-macros = { version = "0.1.0", path = "magnus-macros" }

[target.'cfg(unix)'.dependencies]
rb-sys = { version = "0.9.8", features = ["bindgen-rbimpls", "bindgen-deprecated-types"], optional = true }

[target.'cfg(windows)'.dependencies]
rb-sys = { version = "0.9.8", features = ["link-ruby", "bindgen-rbimpls", "bindgen-deprecated-types"], optional = true }

[build-dependencies]
bindgen = "0.59"

[dev-dependencies]
magnus = { path = ".", features = ["embed"] }

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
