[package]
name = "magnus"
version = "0.5.0"
authors = ["Mat Sadler <mat@sourcetagsandcodes.com>"]
edition = "2018"
resolver = "2"
description = "High level Ruby bindings for Rust."
keywords = ["ruby"]
categories = ["api-bindings", "development-tools::ffi"]
repository = "https://github.com/matsadler/magnus"
homepage = "https://github.com/matsadler/magnus"
documentation = "https://docs.rs/magnus/"
license = "MIT"
exclude = [".github", ".gitignore"]

[workspace]
members = ["magnus-macros"]
exclude = ["examples/rust_blank/ext/rust_blank", "examples/custom_exception_ruby/ext/ahriman", "examples/custom_exception_rust/ext/ahriman"]

[features]
embed = ["rb-sys/link-ruby"]
rb-sys-interop = []
ruby-static = ["rb-sys/ruby-static"]

[dependencies]
magnus-macros = { version = "0.3.0", path = "magnus-macros" }
rb-sys = { version = "0.9.56", default-features = false, features = ["bindgen-rbimpls", "bindgen-deprecated-types"] }

[dev-dependencies]
magnus = { path = ".", features = ["embed", "rb-sys-interop"] }

[build-dependencies]
rb-sys-env = "0.1.1"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[profile.dev]
# Will ensure that the compiler will optimize out any intermediate stack values
# so they are promoted to the heap. This exposes GC bugs in when using
# `GC.stress = true`.
opt-level = 1
