name: Test

on:
- push
- pull_request

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
        - windows-2019
        ruby-version:
        - "2.6"
        - "2.7"
        - "3.0"
        - "3.1"
        - head
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
    - name: Set up Rust
      if: contains(matrix.os, 'windows')
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable-x86_64-pc-windows-gnu
        default: true
    - name: Set LD_LIBRARY_PATH
      if: contains(matrix.os, 'ubuntu')
      run: echo LD_LIBRARY_PATH=$(ruby -e 'print RbConfig::CONFIG["libdir"]') >> $GITHUB_ENV
    - name: Fix clang
      if: contains(matrix.os, 'windows') && (matrix.ruby-version == '3.1' || matrix.ruby-version == 'head')
      run: |
        pacman --remove --cascade mingw-w64-x86_64-clang
        pacman --sync --noconfirm --needed $ENV:MINGW_PACKAGE_PREFIX-clang
    - name: Set up Cargo cache
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
          examples/rust_blank/tmp/
          examples/custom_exception_ruby/tmp/
          examples/custom_exception_rust/tmp/
        key: ${{ runner.os }}-${{ matrix.ruby-version }}-${{ hashFiles('Gemfile') }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Set up build cache
      uses: actions/cache@v3
      with:
        path: |
          target/
          examples/rust_blank/ext/rust_blank/target/
        key: ${{ runner.os }}-ruby-${{ matrix.ruby-version }}-build-${{ hashFiles('**/Cargo.lock') }}
    - name: Example gem tests (blank?)
      working-directory: examples/rust_blank
      run: bundle exec rake test
    - name: Example gem tests (custom exception defined in Ruby)
      if: matrix.ruby-version != 'head'
      working-directory: examples/custom_exception_ruby
      run: bundle exec rake test
    - name: Example gem tests (custom exception defined in Rust)
      if: matrix.ruby-version != 'head'
      working-directory: examples/custom_exception_rust
      run: bundle exec rake test
    - name: Run tests
      run: cargo test
