name: Test

on:
- push
- pull_request

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
        - windows-latest
        ruby-version:
        - "2.6"
        - "2.7"
        - "3.0"
        - "3.1"
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
    - name: Set up Rust
      if: contains(matrix.os, 'windows')
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable-x86_64-pc-windows-gnu
        default: true
    - name: Set LD_LIBRARY_PATH
      if: contains(matrix.os, 'ubuntu')
      run: echo LD_LIBRARY_PATH=$(ruby -e 'print RbConfig::CONFIG["libdir"]') >> $GITHUB_ENV
    - name: Set up Cargo cache
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Set up build cache
      uses: actions/cache@v3
      with:
        path: |
          target/
          examples/rust_blank/ext/rust_blank/target/
        key: ${{ runner.os }}-ruby-${{ matrix.ruby-version }}-build-${{ hashFiles('**/Cargo.lock') }}
    - name: Run tests
      run: cargo test
    - name: Run tests (rb-sys-interop)
      run: cargo test --features rb-sys-interop
    - name: Example gem tests (blank?)
      working-directory: examples/rust_blank
      run: rake test
    - name: Example gem tests (custom exception defined in Ruby)
      working-directory: examples/custom_exception_ruby
      run: rake test
    - name: Example gem tests (custom exception defined in Rust)
      working-directory: examples/custom_exception_rust
      run: rake test
