name: Test

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        ruby-version:
          - "2.6"
          - "2.7"
          - "3.0"
          - "3.1"
          - "3.2"
          - head
        rustup-toolchain:
          - "1.60"
          - stable
        include:
          - os: windows-latest
            ruby-version: mswin
            rustup-toolchain: stable

    steps:
      - uses: actions/checkout@v3

      - uses: oxidize-rb/actions/setup-ruby-and-rust@v1
        with:
          rustup-toolchain: ${{ matrix.rustup-toolchain }}
          ruby-version: ${{ matrix.ruby-version }}
          cache-version: v3
          bundler-cache: true
          cargo-cache: true
          cargo-cache-extra-path: |
            examples/rust_blank/ext/rust_blank/target/
            examples/rust_blank/tmp/
            examples/custom_exception_ruby/tmp/
            examples/custom_exception_rust/tmp/

      - name: Example gem tests (blank?)
        working-directory: examples/rust_blank
        env:
          RB_SYS_STABLE_API_COMPILED_FALLBACK: "1"
        run: bundle exec rake test

      - name: Example gem tests (custom exception defined in Ruby)
        env:
          RB_SYS_STABLE_API_COMPILED_FALLBACK: "1"
        working-directory: examples/custom_exception_ruby
        run: bundle exec rake test

      - name: Example gem tests (custom exception defined in Rust)
        env:
          RB_SYS_STABLE_API_COMPILED_FALLBACK: "1"
        working-directory: examples/custom_exception_rust
        run: bundle exec rake test

      - name: Run tests
        run: cargo test
